language: generic
dist: trusty

aliases:
  -  &linux_deps
    - build-essential
    - automake
    - autoconf
    - bison
    - flex
    - lsb-release
    - libncurses5-dev
    - libtool
  - &linuxgcc
    stage: Testing
    sudo: false
    os: linux
    addons:
      apt:
        sources:
        - ubuntu-toolchain-r-test
        packages:
        - *linux_deps
        - g++-6
  - &linuxclang
    stage: Testing
    os: linux
    # enable sudo for libomp-dev in debian-sid repository
    # It clashes with the existing repo if we add it here.
    sudo: required
    addons:
      apt:
        sources:
        - llvm-toolchain-trusty-4.0
        packages:
        - *linux_deps
        - clang-4.0
  - &linuxpackage
    stage: Packaging
    os: linux
    sudo: false
    compiler: gcc
    addons:
      apt:
        sources:
        - ubuntu-toolchain-r-test
        packages:
        - *linux_deps
        - g++-6
        - devscripts
        - debhelper
        - fakeroot
        - openjdk-7-jdk
  - &osxclang
    stage: Testing
    os: osx
    compiler: clang
    osx_image: xcode8.2
  - &osxpackage
    stage: Packaging
    os: osx
    compiler: clang
    osx_image: xcode8.2
  - &gcc MATRIX_EVAL="CC=gcc-6 && CXX=g++-6"
  - &clang MATRIX_EVAL="CC=clang-4.0 && CXX=clang++-4.0"

jobs:
  include:
  - stage: Style
    # Style check
    os: linux
    compiler: clang
    env: TEST_FORMAT=1
    addons:
      apt:
        sources:
        - llvm-toolchain-trusty-4.0
        packages:
        - clang-format-4.0
    # Linux GCC
  - <<: *linuxgcc
    env:
    - *gcc
    - SOUFFLE_CATEGORY=Evaluation SOUFFLE_CONFS=",-c"
  - <<: *linuxgcc
    env:
    - *gcc
    - SOUFFLE_CATEGORY=Evaluation SOUFFLE_CONFS="-j8,-c -j8"
  - <<: *linuxgcc
    env:
    - *gcc
    - SOUFFLE_CATEGORY=Evaluation SOUFFLE_CONFS="-p profile.log, -c -p profile.log"
  - <<: *linuxgcc
    env:
    - *gcc
    - SOUFFLE_CATEGORY=Unit,Syntactic,Semantic,Interface,Profile,Provenance
  # Linux Clang
  - <<: *linuxclang
    env:
    - *clang
    - SOUFFLE_CATEGORY=Evaluation SOUFFLE_CONFS=",-c"
  - <<: *linuxclang
    env:
    - *clang
    - SOUFFLE_CATEGORY=Evaluation SOUFFLE_CONFS="-j8,-c -j8"
  - <<: *linuxclang
    env:
    - *clang
    - SOUFFLE_CATEGORY=Evaluation SOUFFLE_CONFS="-p profile.log, -c -p profile.log"
  - <<: *linuxclang
    env:
    - *clang
    - SOUFFLE_CATEGORY=Unit,Syntactic,Semantic,Interface,Profile,Provenance
  # OSX Clang
  - <<: *osxclang
    env:
    - SOUFFLE_CATEGORY=Evaluation SOUFFLE_CONFS=",-c"
  - <<: *osxclang
    env:
    - SOUFFLE_CATEGORY=Evaluation SOUFFLE_CONFS="-p profile.log, -c -p profile.log"
  - <<: *osxclang
    env:
    - SOUFFLE_CATEGORY=Unit,Syntactic,Semantic,Interface,Profile,Provenance SOUFFLE_CONFS=",-c,-c -p profile.log,-p profile.log"
  # Make the linux deb packages.
  - <<: *linuxpackage
    env:
    - *gcc
    - MAKEPACKAGE=1
  # Make the OSX deb packages.
  - <<: *osxpackage
    env:
    - MAKEPACKAGE=1

before_install:
  - eval "${MATRIX_EVAL}"
install:
  - "./.travis/install.sh"

before_script:
  - "./.travis/init.sh"
script:
  - "./.travis/run.sh"

after_failure:
  - "./.travis/after_failure.sh"

deploy:
  skip_cleanup: true
  provider: releases
  api_key:
    secure: rWSbE68NuY6ULn7moKvbH1WmOGWljm2R5DwIO6HXmBa8yP3SVk5zSIL/cFoWB5cvqEqIvvRqypRcZuR75lMYefhUq93S/uk8/Sh420g0u3Hcav6wvOmEaQIs/1lkIkIV5GitLKIIXzTgfJ28jnTrrHrVuD6b4bcNJhXcMOxhMG8yeCxgi9DCc3sugBdFPMIOCDU9nb4SCjTq0YluWcTfFzpkD+QtgZzeLyopjldOAAAWx7ZqbpzHxTHJHH/9UZEI8OVDAEhPOawygZaGonUDfVSk04YdPl+Y5pRMXcC2MRVjwaDZVmuHKzJ2QSPwDkr199aONbJLJEpDTBv/ABLIjl+W/js5+hO8jFMdZopFvhOBAhYMka+AQQg860TJhgiXs00Kp/UPGr9OXZnEHWRjdo8KuWz/akOhAvWfnxeoxaBY32V0H1RKIwVvdCE5rekMmJDqgqTJTivIU9w/tDID7I7uvJaZ2bxygMwec+Jfnwlw8iPndWLrU8kVpPkGLVmnllrNAoUvH0wURc9kqwW8pzVyU660yqPNslcFjLIJWWyPgSxI4FcEySu7HaEFy/ukNmLpI+XSpQu8SYofK+xiklkd5fNq7LDn28AvVd8AyZnuBSA3PqzR3Yma1isAsiObcNLtTh6yvx7Nu3GcfcYkmjqFjcpRfww27F+6P0w5Rbk=
  file_glob: true
  file: deploy/*
  on:
    tags: true
