language: cpp
install:
  - sudo apt-get install build-essential g++ automake autoconf bison flex openjdk-7-jdk
compiler:
- gcc
os:
- linux
script: 
- cd souffle
- sh ./bootstrap
- ./configure
- make check 
