sudo: required
dist: trusty
language: cpp
osx_image: xcode7.3
before_install:
  - if [ $TRAVIS_OS_NAME == linux ]; then sudo apt-get -y install debhelper devscripts build-essential g++ automake autoconf bison flex openjdk-7-jdk libboost-all-dev; fi
  - if [ $TRAVIS_OS_NAME == osx ]; then brew update; brew install md5sha1sum bison boost; brew link bison --force; fi
compiler:
- gcc
- clang
os:
- linux
- osx
matrix:
    exclude:
        - os: osx
          compiler: gcc
script: 
- sh ./bootstrap
- ./configure
- make 
- TESTSUITEFLAGS=-j3 make check
- if [ $TRAVIS_OS_NAME == linux ]; then make deb; mkdir deploy; cd packaging; for d in *.deb; do cp $d ../deploy/"$CXX"_"$d"; md5sum <$d >"../deploy/"$CXX"_"$d".md5"; done; cd ..; fi
- if [ $TRAVIS_OS_NAME == osx ]; then make pkg; mkdir deploy; for d in *.pkg; do cp $d deploy/; md5sum <$d >deploy/$d.md5; done; fi
- ls deploy/*
deploy:
  skip_cleanup: true
  provider: releases
  api_key:
    secure: rWSbE68NuY6ULn7moKvbH1WmOGWljm2R5DwIO6HXmBa8yP3SVk5zSIL/cFoWB5cvqEqIvvRqypRcZuR75lMYefhUq93S/uk8/Sh420g0u3Hcav6wvOmEaQIs/1lkIkIV5GitLKIIXzTgfJ28jnTrrHrVuD6b4bcNJhXcMOxhMG8yeCxgi9DCc3sugBdFPMIOCDU9nb4SCjTq0YluWcTfFzpkD+QtgZzeLyopjldOAAAWx7ZqbpzHxTHJHH/9UZEI8OVDAEhPOawygZaGonUDfVSk04YdPl+Y5pRMXcC2MRVjwaDZVmuHKzJ2QSPwDkr199aONbJLJEpDTBv/ABLIjl+W/js5+hO8jFMdZopFvhOBAhYMka+AQQg860TJhgiXs00Kp/UPGr9OXZnEHWRjdo8KuWz/akOhAvWfnxeoxaBY32V0H1RKIwVvdCE5rekMmJDqgqTJTivIU9w/tDID7I7uvJaZ2bxygMwec+Jfnwlw8iPndWLrU8kVpPkGLVmnllrNAoUvH0wURc9kqwW8pzVyU660yqPNslcFjLIJWWyPgSxI4FcEySu7HaEFy/ukNmLpI+XSpQu8SYofK+xiklkd5fNq7LDn28AvVd8AyZnuBSA3PqzR3Yma1isAsiObcNLtTh6yvx7Nu3GcfcYkmjqFjcpRfww27F+6P0w5Rbk=
  file_glob: true
  file: deploy/*
  on:
    repo: souffle-lang/souffle

